### ISSUE TITLE
AttributeError: 'URL' object has no attribute 'decode'` when attempt verify

### ISSUE THREAD

**Issue by hhank** [pyauth/http-message-signatures#1]
On Python 3.10, when attempt to verify the message, the following exception will occur:
`
File "/home/test/.virtualenvs/httpsig/lib/python3.10/site-packages/http_message_signatures/signatures.py", line 173, in verify
    raise InvalidSignature(e) from e
http_message_signatures.exceptions.InvalidSignature: 'URL' object has no attribute 'decode'
`
A further trace:
`Traceback (most recent call last):
  File "/home/test/.virtualenvs/httpsig/lib/python3.10/site-packages/http_message_signatures/signatures.py", line 167, in verify
    sig_base, sig_params_node, sig_elements = self._build_signature_base(
  File "/home/test/.virtualenvs/httpsig/lib/python3.10/site-packages/http_message_signatures/signatures.py", line 44, in _build_signature_base
    component_value = component_resolver.resolve(component_id)
  File "/home/test/.virtualenvs/httpsig/lib/python3.10/site-packages/http_message_signatures/resolvers.py", line 38, in resolve
    return resolver(**component_node.params)
  File "/home/test/.virtualenvs/httpsig/lib/python3.10/site-packages/http_message_signatures/resolvers.py", line 52, in get_authority
    return urllib.parse.urlsplit(self.url).netloc.lower()
  File "/opt/python310/lib/python3.10/urllib/parse.py", line 458, in urlsplit
    url, scheme, _coerce_result = _coerce_args(url, scheme)
  File "/opt/python310/lib/python3.10/urllib/parse.py", line 128, in _coerce_args
    return _decode_args(args) + (_encode_result,)
  File "/opt/python310/lib/python3.10/urllib/parse.py", line 112, in _decode_args
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
  File "/opt/python310/lib/python3.10/urllib/parse.py", line 112, in <genexpr>
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
AttributeError: 'URL' object has no attribute 'decode'`

The `url` assigned to `self.url` in `HTTPSignatureComponentResolver` is a type `yarl.URL`:
https://github.com/pyauth/http-message-signatures/blob/main/http_message_signatures/resolvers.py#L29

I propose to always ensure `self.url` is always a string type as follows:
`
self.url = str(message.url)
`

Will this be an acceptable solution?

Thanks for the considerations.

**Comment by kislyuk** [comment]
Yes, I agree we should explicitly coerce it to string there. Thanks.

**Comment by kislyuk** [comment]
In #18
